// Flat config built on the project-aware config generated by @nuxt/eslint.
// `eslint-config-prettier` is applied last to disable any rules that would
// conflict with Prettier (which owns formatting).
import withNuxt from './.nuxt/eslint.config.mjs'
import prettier from 'eslint-config-prettier'

export default withNuxt(prettier)
